export const adminSchemas = {
  CreateAdminRequest: {
    type: 'object',
    required: ['first_name', 'last_name', 'username', 'email', 'password'],
    properties: {
      first_name:     { type: 'string', minLength: 2, maxLength: 50,  example: 'John' },
      last_name:      { type: 'string', minLength: 2, maxLength: 50,  example: 'Doe' },
      middle_initial: { type: 'string', maxLength: 1,  nullable: true, example: 'A' },
      suffix:         { type: 'string', maxLength: 10, nullable: true, example: 'Jr.' },
      username:       { type: 'string', minLength: 2, maxLength: 50,  example: 'johndoe' },
      email:          { type: 'string', format: 'email',              example: 'john@example.com' },
      password:       { type: 'string', format: 'password', minLength: 8, example: 'secret12345' },
      phone:          { type: 'string', maxLength: 13, nullable: true, example: '09171234567' },
      role:           { type: 'string', enum: ['admin', 'super_admin'], example: 'admin' },
      created_by:     { type: 'string', format: 'uuid', nullable: true, example: '26429db4-6f20-4c60-b7dd-0063b6566c33' },
    },
  },
  UpdateAdminRequest: {
    type: 'object',
    properties: {
      first_name:     { type: 'string', minLength: 2, maxLength: 50,  example: 'John' },
      last_name:      { type: 'string', minLength: 2, maxLength: 50,  example: 'Doe' },
      middle_initial: { type: 'string', maxLength: 1,  nullable: true, example: 'A' },
      suffix:         { type: 'string', maxLength: 10, nullable: true, example: 'Jr.' },
      username:       { type: 'string', minLength: 2, maxLength: 50,  example: 'johndoe' },
      email:          { type: 'string', format: 'email',              example: 'john@example.com' },
      phone:          { type: 'string', maxLength: 13, nullable: true, example: '09171234567' },
      role:           { type: 'string', enum: ['admin', 'super_admin'], example: 'admin' },
    },
  },
  Admin: {
    type: 'object',
    properties: {
      user_id:        { type: 'string', format: 'uuid',    example: '26429db4-6f20-4c60-b7dd-0063b6566c33' },
      first_name:     { type: 'string',                    example: 'John' },
      last_name:      { type: 'string',                    example: 'Doe' },
      middle_initial: { type: 'string', nullable: true,    example: null },
      suffix:         { type: 'string', nullable: true,    example: null },
      username:       { type: 'string',                    example: 'johndoe' },
      email:          { type: 'string',                    example: 'john@example.com' },
      phone:          { type: 'string', nullable: true,    example: null },
      role:           { type: 'string', enum: ['admin', 'super_admin'], example: 'admin' },
      status:         { type: 'string', enum: ['active', 'inactive', 'archived'], example: 'active' },
      created_by:     { type: 'string', format: 'uuid', nullable: true, example: null },
      created_at:     { type: 'string', format: 'date-time', example: '2026-02-26T12:05:24.518177' },
      updated_at:     { type: 'string', format: 'date-time', example: '2026-02-26T12:05:24.518177' },
    },
  },
}