export const clientSchemas = {
CreateClientRequest: {
          type: 'object',
          required: ['first_name', 'last_name', 'username', 'email', 'password'],
          properties: {
            first_name:       { type: 'string', minLength: 2, maxLength: 50, example: 'Maria' },
            last_name:        { type: 'string', minLength: 2, maxLength: 50, example: 'Santos' },
            middle_initial:   { type: 'string', maxLength: 1, nullable: true, example: 'L' },
            suffix:           { type: 'string', maxLength: 10, nullable: true, example: null },
            username:         { type: 'string', minLength: 2, maxLength: 50, example: 'mariasantos' },
            email:            { type: 'string', format: 'email', example: 'maria@example.com' },
            password:         { type: 'string', format: 'password', minLength: 8, example: 'secret12345' },
            phone:            { type: 'string', maxLength: 13, nullable: true, example: '+639181234567' },
            company_name:     { type: 'string', nullable: true, example: 'Santos Enterprises' },
            billing_address:  { type: 'string', nullable: true, example: '123 Rizal Ave, Manila' },
            payment_terms:    { type: 'integer', example: 30 },
            created_by:       { type: 'string', format: 'uuid', nullable: true, example: '26429db4-6f20-4c60-b7dd-0063b6566c33' },
          },
        },
        UpdateClientRequest: {
          type: 'object',
          properties: {
            first_name:       { type: 'string', minLength: 2, maxLength: 50, example: 'Maria' },
            last_name:        { type: 'string', minLength: 2, maxLength: 50, example: 'Santos' },
            middle_initial:   { type: 'string', maxLength: 1, nullable: true, example: 'L' },
            suffix:           { type: 'string', maxLength: 10, nullable: true, example: null },
            username:         { type: 'string', minLength: 2, maxLength: 50, example: 'mariasantos' },
            email:            { type: 'string', format: 'email', example: 'maria@example.com' },
            phone:            { type: 'string', maxLength: 13, nullable: true, example: '+639181234567' },
            company_name:     { type: 'string', nullable: true, example: 'Santos Enterprises' },
            billing_address:  { type: 'string', nullable: true, example: '123 Rizal Ave, Manila' },
            payment_terms:    { type: 'integer', example: 30 },
          },
        },
        Client: {
          type: 'object',
          properties: {
            client_id:        { type: 'string', format: 'uuid', example: '9cbf7585-fbc5-4239-a619-98713d5679c6' },
            user_id:          { type: 'string', format: 'uuid', example: '6752bf65-4148-446f-ab13-c5b91db53b38' },
            first_name:       { type: 'string', example: 'Maria' },
            last_name:        { type: 'string', example: 'Santos' },
            middle_initial:   { type: 'string', nullable: true, example: null },
            suffix:           { type: 'string', nullable: true, example: null },
            username:         { type: 'string', example: 'mariasantos' },
            email:            { type: 'string', example: 'maria@example.com' },
            phone:            { type: 'string', nullable: true, example: null },
            role:             { type: 'string', example: 'client' },
            status:           { type: 'string', enum: ['active', 'inactive', 'archived'], example: 'active' },
            company_name:     { type: 'string', nullable: true, example: 'Santos Enterprises' },
            billing_address:  { type: 'string', nullable: true, example: '123 Rizal Ave, Manila' },
            payment_terms:    { type: 'integer', example: 30 },
            created_by:       { type: 'string', format: 'uuid', nullable: true, example: null },
            created_at:       { type: 'string', format: 'date-time', example: '2026-02-24T05:24:28.849179' },
            updated_at:       { type: 'string', format: 'date-time', example: '2026-02-24T05:24:28.849179' },
          },
        },
}