export const driverSchemas = {
          CreateDriverRequest: {
          type: 'object',
          required: ['first_name', 'last_name', 'username', 'email', 'password', 'license_number', 'license_expiry'],
          properties: {
            first_name:              { type: 'string', minLength: 2, maxLength: 50, example: 'Tom Ervin' },
            last_name:               { type: 'string', minLength: 2, maxLength: 50, example: 'Gomez' },
            middle_name:          { type: 'string', maxLength: 1, nullable: true, example: null },
            suffix:                  { type: 'string', maxLength: 10, nullable: true, example: null },
            username:                { type: 'string', minLength: 2, maxLength: 50, example: 'tomgz' },
            email:                   { type: 'string', format: 'email', example: 'tomervingmz@gmail.com' },
            password:                { type: 'string', format: 'password', minLength: 8, example: 'secret12345' },
            phone:                   { type: 'string', maxLength: 13, nullable: true, example: '09171234567' },
            created_by:              { type: 'string', format: 'uuid', nullable: true, example: '26429db4-6f20-4c60-b7dd-0063b6566c33' },
            license_number:          { type: 'string', maxLength: 50, example: 'N01-12-123456' },
            license_expiry:          { type: 'string', format: 'date', example: '2027-12-31' },
            is_vendor_driver: { type: 'boolean', example: false },
            vendor_id:       { type: 'string', format: 'uuid', nullable: true, example: null },
          },
        },
        UpdateDriverRequest: {
          type: 'object',
          properties: {
            first_name:              { type: 'string', minLength: 2, maxLength: 50, example: 'Tom Ervin' },
            last_name:               { type: 'string', minLength: 2, maxLength: 50, example: 'Gomez' },
            middle_name:          { type: 'string', maxLength: 1, nullable: true, example: null },
            suffix:                  { type: 'string', maxLength: 10, nullable: true, example: null },
            username:                { type: 'string', minLength: 2, maxLength: 50, example: 'tomgz' },
            email:                   { type: 'string', format: 'email', example: 'tomervingmz@gmail.com' },
            phone:                   { type: 'string', maxLength: 13, nullable: true, example: '09171234567' },
            license_number:          { type: 'string', maxLength: 50, example: 'N01-12-123456' },
            license_expiry:          { type: 'string', format: 'date', example: '2027-12-31' },
            is_vendor_driver: { type: 'boolean', example: false },
            vendor_id:       { type: 'string', format: 'uuid', nullable: true, example: null },
          },
        },
        Driver: {
          type: 'object',
          properties: {
            user_id:                 { type: 'string', format: 'uuid', example: 'ade09b28-6f8a-48d4-8d42-5a11bdfdae56' },
            first_name:              { type: 'string', example: 'Tom Ervin' },
            last_name:               { type: 'string', example: 'Gomez' },
            middle_name:          { type: 'string', nullable: true, example: null },
            suffix:                  { type: 'string', nullable: true, example: null },
            username:                { type: 'string', example: 'tomgz' },
            email:                   { type: 'string', example: 'tomervingmz@gmail.com' },
            phone:                   { type: 'string', nullable: true, example: null },
            role:                    { type: 'string', example: 'driver' },
            status:                  { type: 'string', enum: ['available', 'assigned', 'on_leave', 'inactive'], example: 'available' },
            created_at:              { type: 'string', format: 'date-time', example: '2026-02-22T12:47:52.044911' },
            updated_at:              { type: 'string', format: 'date-time', example: '2026-02-22T12:47:52.044911' },
            license_number:          { type: 'string', example: 'N01-12-123456' },
            license_expiry:          { type: 'string', format: 'date', example: '2027-12-31' },
            is_vendor_driver: { type: 'boolean', example: false },
            vendor_id:       { type: 'string', format: 'uuid', nullable: true, example: null },
          },
        },
}