export const generalManagerSchemas = {
  CreateGeneralManagerRequest: {
    type: 'object',
    required: ['first_name', 'last_name', 'username', 'email'],
    properties: {
      first_name:     { type: 'string', minLength: 2, maxLength: 50, example: 'Jane' },
      last_name:      { type: 'string', minLength: 2, maxLength: 50, example: 'Smith' },
      middle_initial: { type: 'string', maxLength: 1, nullable: true, example: null },
      suffix:         { type: 'string', maxLength: 10, nullable: true, example: null },
      username:       { type: 'string', minLength: 2, maxLength: 50, example: 'janesmith' },
      email:          { type: 'string', format: 'email', example: 'jane@example.com' },
      phone:          { type: 'string', maxLength: 16, nullable: true, example: '+639171234567' },
      created_by:     { type: 'string', format: 'uuid', nullable: true, example: null },
    },
  },
  UpdateGeneralManagerRequest: {
    type: 'object',
    properties: {
      first_name:     { type: 'string', minLength: 2, maxLength: 50, example: 'Jane' },
      last_name:      { type: 'string', minLength: 2, maxLength: 50, example: 'Smith' },
      middle_initial: { type: 'string', maxLength: 1, nullable: true, example: null },
      suffix:         { type: 'string', maxLength: 10, nullable: true, example: null },
      username:       { type: 'string', minLength: 2, maxLength: 50, example: 'janesmith' },
      email:          { type: 'string', format: 'email', example: 'jane@example.com' },
      phone:          { type: 'string', maxLength: 16, nullable: true, example: '+639171234567' },
    },
  },
  GeneralManager: {
    type: 'object',
    properties: {
      user_id:        { type: 'string', format: 'uuid', example: 'ade09b28-6f8a-48d4-8d42-5a11bdfdae56' },
      first_name:     { type: 'string', example: 'Jane' },
      last_name:      { type: 'string', example: 'Smith' },
      middle_initial: { type: 'string', nullable: true, example: null },
      suffix:         { type: 'string', nullable: true, example: null },
      username:       { type: 'string', example: 'janesmith' },
      email:          { type: 'string', example: 'jane@example.com' },
      phone:          { type: 'string', nullable: true, example: null },
      role:           { type: 'string', example: 'general_manager' },
      status:         { type: 'string', enum: ['active', 'inactive', 'archived'], example: 'active' },
      created_at:     { type: 'string', format: 'date-time' },
      updated_at:     { type: 'string', format: 'date-time' },
      created_by:     { type: 'string', format: 'uuid', nullable: true },
    },
  },
}
