export const vendorSchemas = {
  CreateVendorRequest: {
          type: 'object',
          required: ['first_name', 'last_name', 'username', 'email', 'vendor_type'],
          properties: {
            first_name:     { type: 'string', minLength: 2, maxLength: 50, example: 'Pedro' },
            last_name:      { type: 'string', minLength: 2, maxLength: 50, example: 'Reyes' },
            middle_name: { type: 'string', maxLength: 1, nullable: true, example: 'B' },
            suffix:         { type: 'string', maxLength: 10, nullable: true, example: null },
            username:       { type: 'string', minLength: 2, maxLength: 50, example: 'pedroreyes' },
            email:          { type: 'string', format: 'email', example: 'pedro@example.com' },
            phone:          { type: 'string', maxLength: 13, nullable: true, example: '09191234567' },
            vendor_type:    { type: 'string', enum: ['individual', 'company'], example: 'company' },
            company_name:   { type: 'string', nullable: true, example: 'Reyes Trucking Co.' },
            business_permit: { type: 'string', nullable: true, example: 'BP-2026-00123' },
            created_by:     { type: 'string', format: 'uuid', nullable: true, example: '26429db4-6f20-4c60-b7dd-0063b6566c33' },
          },
        },
        UpdateVendorRequest: {
          type: 'object',
          properties: {
            first_name:     { type: 'string', minLength: 2, maxLength: 50, example: 'Pedro' },
            last_name:      { type: 'string', minLength: 2, maxLength: 50, example: 'Reyes' },
            middle_name: { type: 'string', maxLength: 1, nullable: true, example: 'B' },
            suffix:         { type: 'string', maxLength: 10, nullable: true, example: null },
            username:       { type: 'string', minLength: 2, maxLength: 50, example: 'pedroreyes' },
            email:          { type: 'string', format: 'email', example: 'pedro@example.com' },
            phone:          { type: 'string', maxLength: 13, nullable: true, example: '09191234567' },
            vendor_type:    { type: 'string', enum: ['individual', 'company'], example: 'company' },
            company_name:   { type: 'string', nullable: true, example: 'Reyes Trucking Co.' },
            business_permit: { type: 'string', nullable: true, example: 'BP-2026-00123' },
          },
        },
        Vendor: {
          type: 'object',
          properties: {
            vendor_id:      { type: 'string', format: 'uuid', example: '7a1b2c3d-4e5f-6789-abcd-ef0123456789' },
            user_id:        { type: 'string', format: 'uuid', example: 'a1b2c3d4-e5f6-7890-abcd-ef0123456789' },
            first_name:     { type: 'string', example: 'Pedro' },
            last_name:      { type: 'string', example: 'Reyes' },
            middle_name: { type: 'string', nullable: true, example: 'B' },
            suffix:         { type: 'string', nullable: true, example: null },
            username:       { type: 'string', example: 'pedroreyes' },
            email:          { type: 'string', example: 'pedro@example.com' },
            phone:          { type: 'string', nullable: true, example: '09191234567' },
            role:           { type: 'string', example: 'vendor' },
            status:         { type: 'string', enum: ['active', 'inactive', 'archived'], example: 'active' },
            vendor_type:    { type: 'string', enum: ['individual', 'company'], example: 'company' },
            company_name:   { type: 'string', nullable: true, example: 'Reyes Trucking Co.' },
            business_permit: { type: 'string', nullable: true, example: 'BP-2026-00123' },
            created_at:     { type: 'string', format: 'date-time', example: '2026-02-26T08:00:00.000000' },
            updated_at:     { type: 'string', format: 'date-time', example: '2026-02-26T08:00:00.000000' },
          },
        },
}