import swaggerJsdoc from 'swagger-jsdoc'

const options: swaggerJsdoc.Options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Logistics Backend API',
      version: '1.0.0',
      description: 'Logistics Backend REST API',
    },
    servers: [
      {
        url: 'http://localhost:4000/api',
        description: 'Development',
      },
    ],
    tags: [
      { name: 'Admins',         description: 'Admin management' },
      { name: 'Drivers',        description: 'Driver management' },
      { name: 'Clients',        description: 'Client management' },
      { name: 'Subcontractors', description: 'Subcontractor management' },
    ],
    components: {
      schemas: {

        CreateAdminRequest: {
          type: 'object',
          required: ['first_name', 'last_name', 'username', 'email', 'password'],
          properties: {
            first_name:     { type: 'string', minLength: 2, maxLength: 50,  example: 'John' },
            last_name:      { type: 'string', minLength: 2, maxLength: 50,  example: 'Doe' },
            middle_initial: { type: 'string', maxLength: 1,  nullable: true, example: 'A' },
            suffix:         { type: 'string', maxLength: 10, nullable: true, example: 'Jr.' },
            username:       { type: 'string', minLength: 2, maxLength: 50,  example: 'johndoe' },
            email:          { type: 'string', format: 'email',              example: 'john@example.com' },
            password:       { type: 'string', format: 'password', minLength: 8, example: 'secret12345' },
            phone:          { type: 'string', maxLength: 13, nullable: true, example: '+639171234567' },
            role:           { type: 'string', enum: ['admin', 'super_admin'], example: 'admin' },
            created_by:     { type: 'string', format: 'uuid', nullable: true, example: '26429db4-6f20-4c60-b7dd-0063b6566c33' },
          },
        },
        UpdateAdminRequest: {
          type: 'object',
          properties: {
            first_name:     { type: 'string', minLength: 2, maxLength: 50,  example: 'John' },
            last_name:      { type: 'string', minLength: 2, maxLength: 50,  example: 'Doe' },
            middle_initial: { type: 'string', maxLength: 1,  nullable: true, example: 'A' },
            suffix:         { type: 'string', maxLength: 10, nullable: true, example: 'Jr.' },
            username:       { type: 'string', minLength: 2, maxLength: 50,  example: 'johndoe' },
            email:          { type: 'string', format: 'email',              example: 'john@example.com' },
            phone:          { type: 'string', maxLength: 13, nullable: true, example: '+639171234567' },
            role:           { type: 'string', enum: ['admin', 'super_admin'], example: 'admin' },
          },
        },
        Admin: {
          type: 'object',
          properties: {
            user_id:        { type: 'string', format: 'uuid',    example: '26429db4-6f20-4c60-b7dd-0063b6566c33' },
            first_name:     { type: 'string',                    example: 'John' },
            last_name:      { type: 'string',                    example: 'Doe' },
            middle_initial: { type: 'string', nullable: true,    example: null },
            suffix:         { type: 'string', nullable: true,    example: null },
            username:       { type: 'string',                    example: 'johndoe' },
            email:          { type: 'string',                    example: 'john@example.com' },
            phone:          { type: 'string', nullable: true,    example: null },
            role:           { type: 'string', enum: ['admin', 'super_admin'], example: 'admin' },
            status:         { type: 'string', enum: ['active', 'inactive', 'archived'], example: 'active' },
            created_by:     { type: 'string', format: 'uuid', nullable: true, example: null },
            created_at:     { type: 'string', format: 'date-time', example: '2026-02-26T12:05:24.518177' },
            updated_at:     { type: 'string', format: 'date-time', example: '2026-02-26T12:05:24.518177' },
          },
        },

        CreateDriverRequest: {
          type: 'object',
          required: ['first_name', 'last_name', 'username', 'email', 'password', 'license_number', 'license_expiry'],
          properties: {
            first_name:              { type: 'string', minLength: 2, maxLength: 50, example: 'Tom Ervin' },
            last_name:               { type: 'string', minLength: 2, maxLength: 50, example: 'Gomez' },
            middle_initial:          { type: 'string', maxLength: 1, nullable: true, example: null },
            suffix:                  { type: 'string', maxLength: 10, nullable: true, example: null },
            username:                { type: 'string', minLength: 2, maxLength: 50, example: 'tomgz' },
            email:                   { type: 'string', format: 'email', example: 'tomervingmz@gmail.com' },
            password:                { type: 'string', format: 'password', minLength: 8, example: 'secret12345' },
            phone:                   { type: 'string', maxLength: 13, nullable: true, example: '+639171234567' },
            created_by:              { type: 'string', format: 'uuid', nullable: true, example: '26429db4-6f20-4c60-b7dd-0063b6566c33' },
            license_number:          { type: 'string', maxLength: 50, example: 'N01-12-123456' },
            license_expiry:          { type: 'string', format: 'date', example: '2027-12-31' },
            is_subcontractor_driver: { type: 'boolean', example: false },
            subcontractor_id:        { type: 'string', format: 'uuid', nullable: true, example: null },
          },
        },
        UpdateDriverRequest: {
          type: 'object',
          properties: {
            first_name:              { type: 'string', minLength: 2, maxLength: 50, example: 'Tom Ervin' },
            last_name:               { type: 'string', minLength: 2, maxLength: 50, example: 'Gomez' },
            middle_initial:          { type: 'string', maxLength: 1, nullable: true, example: null },
            suffix:                  { type: 'string', maxLength: 10, nullable: true, example: null },
            username:                { type: 'string', minLength: 2, maxLength: 50, example: 'tomgz' },
            email:                   { type: 'string', format: 'email', example: 'tomervingmz@gmail.com' },
            phone:                   { type: 'string', maxLength: 13, nullable: true, example: '+639171234567' },
            license_number:          { type: 'string', maxLength: 50, example: 'N01-12-123456' },
            license_expiry:          { type: 'string', format: 'date', example: '2027-12-31' },
            is_subcontractor_driver: { type: 'boolean', example: false },
            subcontractor_id:        { type: 'string', format: 'uuid', nullable: true, example: null },
          },
        },
        Driver: {
          type: 'object',
          properties: {
            user_id:                 { type: 'string', format: 'uuid', example: 'ade09b28-6f8a-48d4-8d42-5a11bdfdae56' },
            first_name:              { type: 'string', example: 'Tom Ervin' },
            last_name:               { type: 'string', example: 'Gomez' },
            middle_initial:          { type: 'string', nullable: true, example: null },
            suffix:                  { type: 'string', nullable: true, example: null },
            username:                { type: 'string', example: 'tomgz' },
            email:                   { type: 'string', example: 'tomervingmz@gmail.com' },
            phone:                   { type: 'string', nullable: true, example: null },
            role:                    { type: 'string', example: 'driver' },
            status:                  { type: 'string', enum: ['available', 'assigned', 'on_leave', 'inactive'], example: 'available' },
            created_at:              { type: 'string', format: 'date-time', example: '2026-02-22T12:47:52.044911' },
            updated_at:              { type: 'string', format: 'date-time', example: '2026-02-22T12:47:52.044911' },
            license_number:          { type: 'string', example: 'N01-12-123456' },
            license_expiry:          { type: 'string', format: 'date', example: '2027-12-31' },
            is_subcontractor_driver: { type: 'boolean', example: false },
            subcontractor_id:        { type: 'string', format: 'uuid', nullable: true, example: null },
          },
        },

        CreateClientRequest: {
          type: 'object',
          required: ['first_name', 'last_name', 'username', 'email', 'password'],
          properties: {
            first_name:       { type: 'string', minLength: 2, maxLength: 50, example: 'Maria' },
            last_name:        { type: 'string', minLength: 2, maxLength: 50, example: 'Santos' },
            middle_initial:   { type: 'string', maxLength: 1, nullable: true, example: 'L' },
            suffix:           { type: 'string', maxLength: 10, nullable: true, example: null },
            username:         { type: 'string', minLength: 2, maxLength: 50, example: 'mariasantos' },
            email:            { type: 'string', format: 'email', example: 'maria@example.com' },
            password:         { type: 'string', format: 'password', minLength: 8, example: 'secret12345' },
            phone:            { type: 'string', maxLength: 13, nullable: true, example: '+639181234567' },
            company_name:     { type: 'string', nullable: true, example: 'Santos Enterprises' },
            billing_address:  { type: 'string', nullable: true, example: '123 Rizal Ave, Manila' },
            payment_terms:    { type: 'integer', example: 30 },
            created_by:       { type: 'string', format: 'uuid', nullable: true, example: '26429db4-6f20-4c60-b7dd-0063b6566c33' },
          },
        },
        UpdateClientRequest: {
          type: 'object',
          properties: {
            first_name:       { type: 'string', minLength: 2, maxLength: 50, example: 'Maria' },
            last_name:        { type: 'string', minLength: 2, maxLength: 50, example: 'Santos' },
            middle_initial:   { type: 'string', maxLength: 1, nullable: true, example: 'L' },
            suffix:           { type: 'string', maxLength: 10, nullable: true, example: null },
            username:         { type: 'string', minLength: 2, maxLength: 50, example: 'mariasantos' },
            email:            { type: 'string', format: 'email', example: 'maria@example.com' },
            phone:            { type: 'string', maxLength: 13, nullable: true, example: '+639181234567' },
            company_name:     { type: 'string', nullable: true, example: 'Santos Enterprises' },
            billing_address:  { type: 'string', nullable: true, example: '123 Rizal Ave, Manila' },
            payment_terms:    { type: 'integer', example: 30 },
          },
        },
        Client: {
          type: 'object',
          properties: {
            client_id:        { type: 'string', format: 'uuid', example: '9cbf7585-fbc5-4239-a619-98713d5679c6' },
            user_id:          { type: 'string', format: 'uuid', example: '6752bf65-4148-446f-ab13-c5b91db53b38' },
            first_name:       { type: 'string', example: 'Maria' },
            last_name:        { type: 'string', example: 'Santos' },
            middle_initial:   { type: 'string', nullable: true, example: null },
            suffix:           { type: 'string', nullable: true, example: null },
            username:         { type: 'string', example: 'mariasantos' },
            email:            { type: 'string', example: 'maria@example.com' },
            phone:            { type: 'string', nullable: true, example: null },
            role:             { type: 'string', example: 'client' },
            status:           { type: 'string', enum: ['active', 'inactive', 'archived'], example: 'active' },
            company_name:     { type: 'string', nullable: true, example: 'Santos Enterprises' },
            billing_address:  { type: 'string', nullable: true, example: '123 Rizal Ave, Manila' },
            payment_terms:    { type: 'integer', example: 30 },
            created_by:       { type: 'string', format: 'uuid', nullable: true, example: null },
            created_at:       { type: 'string', format: 'date-time', example: '2026-02-24T05:24:28.849179' },
            updated_at:       { type: 'string', format: 'date-time', example: '2026-02-24T05:24:28.849179' },
          },
        },

        CreateSubcontractorRequest: {
          type: 'object',
          required: ['first_name', 'last_name', 'username', 'email', 'password', 'subcontractor_type'],
          properties: {
            first_name:          { type: 'string', minLength: 2, maxLength: 50, example: 'Pedro' },
            last_name:           { type: 'string', minLength: 2, maxLength: 50, example: 'Reyes' },
            middle_initial:      { type: 'string', maxLength: 1, nullable: true, example: 'B' },
            suffix:              { type: 'string', maxLength: 10, nullable: true, example: null },
            username:            { type: 'string', minLength: 2, maxLength: 50, example: 'pedroreyes' },
            email:               { type: 'string', format: 'email', example: 'pedro@example.com' },
            password:            { type: 'string', format: 'password', minLength: 8, example: 'secret12345' },
            phone:               { type: 'string', maxLength: 13, nullable: true, example: '+639191234567' },
            subcontractor_type:  { type: 'string', enum: ['individual', 'company'], example: 'company' },
            company_name:        { type: 'string', nullable: true, example: 'Reyes Trucking Co.' },
            business_permit:     { type: 'string', nullable: true, example: 'BP-2026-00123' },
            created_by:          { type: 'string', format: 'uuid', nullable: true, example: '26429db4-6f20-4c60-b7dd-0063b6566c33' },
          },
        },
        UpdateSubcontractorRequest: {
          type: 'object',
          properties: {
            first_name:          { type: 'string', minLength: 2, maxLength: 50, example: 'Pedro' },
            last_name:           { type: 'string', minLength: 2, maxLength: 50, example: 'Reyes' },
            middle_initial:      { type: 'string', maxLength: 1, nullable: true, example: 'B' },
            suffix:              { type: 'string', maxLength: 10, nullable: true, example: null },
            username:            { type: 'string', minLength: 2, maxLength: 50, example: 'pedroreyes' },
            email:               { type: 'string', format: 'email', example: 'pedro@example.com' },
            phone:               { type: 'string', maxLength: 13, nullable: true, example: '+639191234567' },
            subcontractor_type:  { type: 'string', enum: ['individual', 'company'], example: 'company' },
            company_name:        { type: 'string', nullable: true, example: 'Reyes Trucking Co.' },
            business_permit:     { type: 'string', nullable: true, example: 'BP-2026-00123' },
          },
        },
        Subcontractor: {
          type: 'object',
          properties: {
            subcontractor_id:    { type: 'string', format: 'uuid', example: '7a1b2c3d-4e5f-6789-abcd-ef0123456789' },
            user_id:             { type: 'string', format: 'uuid', example: 'a1b2c3d4-e5f6-7890-abcd-ef0123456789' },
            first_name:          { type: 'string', example: 'Pedro' },
            last_name:           { type: 'string', example: 'Reyes' },
            middle_initial:      { type: 'string', nullable: true, example: 'B' },
            suffix:              { type: 'string', nullable: true, example: null },
            username:            { type: 'string', example: 'pedroreyes' },
            email:               { type: 'string', example: 'pedro@example.com' },
            phone:               { type: 'string', nullable: true, example: '+639191234567' },
            role:                { type: 'string', example: 'subcontractor' },
            status:              { type: 'string', enum: ['active', 'inactive', 'archived'], example: 'active' },
            subcontractor_type:  { type: 'string', enum: ['individual', 'company'], example: 'company' },
            company_name:        { type: 'string', nullable: true, example: 'Reyes Trucking Co.' },
            business_permit:     { type: 'string', nullable: true, example: 'BP-2026-00123' },
            created_at:          { type: 'string', format: 'date-time', example: '2026-02-26T08:00:00.000000' },
            updated_at:          { type: 'string', format: 'date-time', example: '2026-02-26T08:00:00.000000' },
          },
        },

      },
    },
  },
  apis: ['./src/routes/**/*.ts'],
}

export const swaggerSpec = swaggerJsdoc(options)